### ISSUE TITLE
File does not exist: for log reg training

### ISSUE THREAD

**Issue by achaubal** [WinVector/Logistic#1]
Hi,

I am trying to run the logistic regression training and get an error java.io.FileNotFoundException: File does not exist: /user/ameet/test.csv I tried both dir and file but same result

I have tried both plain java and hadoop modes and get the same issue.
in Java, plain file system, I get following result:
 java -cp WinVectorLogistic.Hadoop0.20.2.jar:commons-cli-1.2.jar:hadoop-0.20.2-cdh3u2-core.jar:commons-logging-api-1.0.4.jar:commons-logging-1.0.4.jar com.winvector.logistic.LogisticTrain -trainURI test.csv -formula "col4 ~ col1 + col2 + col3"
Feb 22, 2012 9:58:44 AM com.winvector.logistic.LogisticTrain main
INFO: start LogisticTrain       Wed Feb 22 09:58:44 EST 2012
Feb 22, 2012 9:58:44 AM com.winvector.logistic.LogisticTrain main
INFO:  source URI: /mnt/home/ameet/bofa/ML/logistic/uciCarTrain.tsv
Feb 22, 2012 9:58:44 AM com.winvector.logistic.LogisticTrain main
INFO: trainer: class com.winvector.logistic.LogisticTrain
Exception in thread "main" java.lang.RuntimeException: java.lang.IllegalArgumentException: URI is not absolute
        at com.winvector.util.TrivialReader.iterator(TrivialReader.java:203)
        at com.winvector.util.TrivialReader.iterator(TrivialReader.java:1)
        at com.winvector.logistic.LogisticTrain.buildVariableDefs(LogisticTrain.java:48)
        at com.winvector.logistic.LogisticTrain.buildAdpater(LogisticTrain.java:60)
        at com.winvector.logistic.LogisticTrain.train(LogisticTrain.java:272)
        at com.winvector.logistic.LogisticTrain.run(LogisticTrain.java:291)
        at com.winvector.logistic.LogisticTrain.main(LogisticTrain.java:258)
Caused by: java.lang.IllegalArgumentException: URI is not absolute
        at java.net.URI.toURL(URI.java:1079)
        at com.winvector.util.TrivialReader.openBufferedReader(TrivialReader.java:82)
        at com.winvector.util.TrivialReader.iterator(TrivialReader.java:201)
        ... 6 more

and in hadoop:
java.io.FileNotFoundException: File does not exist: /user/ameet/test.csv
        at org.apache.hadoop.hdfs.DFSClient$DFSInputStream.openInfo(DFSClient.java:1602)
        at org.apache.hadoop.hdfs.DFSClient$DFSInputStream.<init>(DFSClient.java:1593)
        at org.apache.hadoop.hdfs.DFSClient.open(DFSClient.java:428)
        at org.apache.hadoop.hdfs.DistributedFileSystem.open(DistributedFileSystem.java:187)
        at org.apache.hadoop.fs.FileSystem.open(FileSystem.java:456)
        at com.winvector.logistic.mr.WritableUtils.readFirstLine(WritableUtils.java:39)
        at com.winvector.logistic.demo.MapReduceLogisticTrain.run(MapReduceLogisticTrain.java:64)
        at com.winvector.logistic.demo.MapReduceLogisticTrain.run(MapReduceLogisticTrain.java:51)
        at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:65)
        at com.winvector.logistic.demo.MapReduceLogisticTrain.main(MapReduceLogisticTrain.java:108)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.apache.hadoop.util.ProgramDriver$ProgramDescription.invoke(ProgramDriver.java:68)
        at org.apache.hadoop.util.ProgramDriver.driver(ProgramDriver.java:139)
        at com.winvector.logistic.demo.DemoDriver.main(DemoDriver.java:21)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.apache.hadoop.util.RunJar.main(RunJar.java:186)
Exception in thread "main" java.lang.Exception: java.io.FileNotFoundException: File does not exist: /user/ameet/test.csv
        at com.winvector.logistic.demo.DemoDriver.main(DemoDriver.java:25)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.apache.hadoop.util.RunJar.main(RunJar.java:186)

what am I doing wrong?

thanks

ameet

**Comment by WinVector** [comment]
Hi Ameet,

The input is a URI so for a file you need to add the tag "file:"  so probably you want to load file:test.csv as your input.

John

On Feb 22, 2012, at 7:00 AM, achaubal wrote:

> Hi,
> 
> I am trying to run the logistic regression training and get an error java.io.FileNotFoundException: File does not exist: /user/ameet/test.csv
> 
> I have tried both plain java and hadoop modes and get the same issue.
> in Java, plain file system, I get following result:
> java -cp WinVectorLogistic.Hadoop0.20.2.jar:commons-cli-1.2.jar:hadoop-0.20.2-cdh3u2-core.jar:commons-logging-api-1.0.4.jar:commons-logging-1.0.4.jar com.winvector.logistic.LogisticTrain -trainURI test.csv -formula "col4 ~ col1 + col2 + col3"
> Feb 22, 2012 9:58:44 AM com.winvector.logistic.LogisticTrain main
> INFO: start LogisticTrain       Wed Feb 22 09:58:44 EST 2012
> Feb 22, 2012 9:58:44 AM com.winvector.logistic.LogisticTrain main
> INFO:  source URI: /mnt/home/ameet/bofa/ML/logistic/uciCarTrain.tsv
> Feb 22, 2012 9:58:44 AM com.winvector.logistic.LogisticTrain main
> INFO: trainer: class com.winvector.logistic.LogisticTrain
> Exception in thread "main" java.lang.RuntimeException: java.lang.IllegalArgumentException: URI is not absolute
>        at com.winvector.util.TrivialReader.iterator(TrivialReader.java:203)
>        at com.winvector.util.TrivialReader.iterator(TrivialReader.java:1)
>        at com.winvector.logistic.LogisticTrain.buildVariableDefs(LogisticTrain.java:48)
>        at com.winvector.logistic.LogisticTrain.buildAdpater(LogisticTrain.java:60)
>        at com.winvector.logistic.LogisticTrain.train(LogisticTrain.java:272)
>        at com.winvector.logistic.LogisticTrain.run(LogisticTrain.java:291)
>        at com.winvector.logistic.LogisticTrain.main(LogisticTrain.java:258)
> Caused by: java.lang.IllegalArgumentException: URI is not absolute
>        at java.net.URI.toURL(URI.java:1079)
>        at com.winvector.util.TrivialReader.openBufferedReader(TrivialReader.java:82)
>        at com.winvector.util.TrivialReader.iterator(TrivialReader.java:201)
>        ... 6 more
> 
> and in hadoop:
> java.io.FileNotFoundException: File does not exist: /user/ameet/test.csv
>        at org.apache.hadoop.hdfs.DFSClient$DFSInputStream.openInfo(DFSClient.java:1602)
>        at org.apache.hadoop.hdfs.DFSClient$DFSInputStream.<init>(DFSClient.java:1593)
>        at org.apache.hadoop.hdfs.DFSClient.open(DFSClient.java:428)
>        at org.apache.hadoop.hdfs.DistributedFileSystem.open(DistributedFileSystem.java:187)
>        at org.apache.hadoop.fs.FileSystem.open(FileSystem.java:456)
>        at com.winvector.logistic.mr.WritableUtils.readFirstLine(WritableUtils.java:39)
>        at com.winvector.logistic.demo.MapReduceLogisticTrain.run(MapReduceLogisticTrain.java:64)
>        at com.winvector.logistic.demo.MapReduceLogisticTrain.run(MapReduceLogisticTrain.java:51)
>        at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:65)
>        at com.winvector.logistic.demo.MapReduceLogisticTrain.main(MapReduceLogisticTrain.java:108)
>        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
>        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
>        at java.lang.reflect.Method.invoke(Method.java:597)
>        at org.apache.hadoop.util.ProgramDriver$ProgramDescription.invoke(ProgramDriver.java:68)
>        at org.apache.hadoop.util.ProgramDriver.driver(ProgramDriver.java:139)
>        at com.winvector.logistic.demo.DemoDriver.main(DemoDriver.java:21)
>        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
>        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
>        at java.lang.reflect.Method.invoke(Method.java:597)
>        at org.apache.hadoop.util.RunJar.main(RunJar.java:186)
> Exception in thread "main" java.lang.Exception: java.io.FileNotFoundException: File does not exist: /user/ameet/test.csv
>        at com.winvector.logistic.demo.DemoDriver.main(DemoDriver.java:25)
>        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
>        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
>        at java.lang.reflect.Method.invoke(Method.java:597)
>        at org.apache.hadoop.util.RunJar.main(RunJar.java:186)
> 
> what am I doing wrong?
> 
> thanks
> 
> ameet
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/WinVector/SQL-Screwdriver/issues/1

---

John Mount
http://www.win-vector.com/
http://www.win-vector.com/blog/
jmount@win-vector.com

**Comment by achaubal** [comment]
ok, got that, so after adding the URI as
trainURI file:///mnt/home/../..../uciCarTrain.tsv it worked.

next it didn't find a class, 
Exception in thread "main" java.lang.NoClassDefFoundError: cern/colt/matrix/DoubleMatrix2D

after searching on the internet, found the colt.jar from http://acs.lbl.gov/software/colt/ downloaded and added that to my classpath and now, the regression prints the output. 

How do I do this in hadoop. what is the URI in hadoop ?
Also how do I refer to the colt.jar in hadoop ?

thanks

ameet

**Comment by WinVector** [comment]
adding the jars in Hadoop is a bit implementation dependent.  sorry the colt dependence leaked in (it wasn't supposed to be there).  i'll likely build a new jar with the dependence removed tonight.

**Comment by achaubal** [comment]
thanks. what about Hadoop? what's the format of trainURI?
I tried file:/// or just plain filename, but it's not working.
it keeps saying file not found:
java.io.FileNotFoundException: File does not exist: /user/ameet/test.csv
        at org.apache.hadoop.hdfs.DFSClient$DFSInputStream.openInfo(DFSClient.java:1602)
        at org.apache.hadoop.hdfs.DFSClient$DFSInputStream.<init>(DFSClient.java:1593)
        at org.apache.hadoop.hdfs.DFSClient.open(DFSClient.java:428)
        at org.apache.hadoop.hdfs.DistributedFileSystem.open(DistributedFileSystem.java:187)
        at org.apache.hadoop.fs.FileSystem.open(FileSystem.java:456)
        at com.winvector.logistic.mr.WritableUtils.readFirstLine(WritableUtils.java:39)
        at com.winvector.logistic.demo.MapReduceLogisticTrain.run(MapReduceLogisticTrain.java:64)
        at com.winvector.logistic.demo.MapReduceLogisticTrain.run(MapReduceLogisticTrain.java:51)
        at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:65)
        at com.winvector.logistic.demo.MapReduceLogisticTrain.main(MapReduceLogisticTrain.java:108)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.apache.hadoop.util.ProgramDriver$ProgramDescription.invoke(ProgramDriver.java:68)
        at org.apache.hadoop.util.ProgramDriver.driver(ProgramDriver.java:139)
        at com.winvector.logistic.demo.DemoDriver.main(DemoDriver.java:21)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.apache.hadoop.util.RunJar.main(RunJar.java:186)
Exception in thread "main" java.lang.Exception: java.io.FileNotFoundException: File does not exist: /user/ameet/test.csv
        at com.winvector.logistic.demo.DemoDriver.main(DemoDriver.java:25)
        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
        at java.lang.reflect.Method.invoke(Method.java:597)
        at org.apache.hadoop.util.RunJar.main(RunJar.java:186)

**Comment by WinVector** [comment]
I have removed the colt dependence (updated both the jar and the git repository).  Sorry about the trouble.

On Feb 22, 2012, at 7:44 AM, achaubal wrote:

> ok, got that, so after adding the URI as
> trainURI file:///mnt/home/../..../uciCarTrain.tsv it worked.
> 
> next it didn't find a class, 
> Exception in thread "main" java.lang.NoClassDefFoundError: cern/colt/matrix/DoubleMatrix2D
> 
> after searching on the internet, found the colt.jar from http://acs.lbl.gov/software/colt/ downloaded and added that to my classpath and now, the regression prints the output. 
> 
> How do I do this in hadoop. what is the URI in hadoop ?
> Also how do I refer to the colt.jar in hadoop ?
> 
> thanks
> 
> ameet
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/WinVector/SQL-Screwdriver/issues/1#issuecomment-4106502

---

John Mount
http://www.win-vector.com/
http://www.win-vector.com/blog/
jmount@win-vector.com

**Comment by WinVector** [comment]
I think the format is file: without the slashes (for directories relative to where your stuff is).  But on Amazon ec2 you have to use s3n:/ (as the URI type of S3 file buckets).  Unfortunately Hadoop file URIs are very installation dependent (some allow absolute paths, some do not and so on).

John

On Feb 22, 2012, at 4:40 PM, achaubal wrote:

> thanks. what about Hadoop? what's the format of trainURI?
> I tried file:/// or just plain filename, but it's not working.
> it keeps saying file not found:
> java.io.FileNotFoundException: File does not exist: /user/ameet/test.csv
>        at org.apache.hadoop.hdfs.DFSClient$DFSInputStream.openInfo(DFSClient.java:1602)
>        at org.apache.hadoop.hdfs.DFSClient$DFSInputStream.<init>(DFSClient.java:1593)
>        at org.apache.hadoop.hdfs.DFSClient.open(DFSClient.java:428)
>        at org.apache.hadoop.hdfs.DistributedFileSystem.open(DistributedFileSystem.java:187)
>        at org.apache.hadoop.fs.FileSystem.open(FileSystem.java:456)
>        at com.winvector.logistic.mr.WritableUtils.readFirstLine(WritableUtils.java:39)
>        at com.winvector.logistic.demo.MapReduceLogisticTrain.run(MapReduceLogisticTrain.java:64)
>        at com.winvector.logistic.demo.MapReduceLogisticTrain.run(MapReduceLogisticTrain.java:51)
>        at org.apache.hadoop.util.ToolRunner.run(ToolRunner.java:65)
>        at com.winvector.logistic.demo.MapReduceLogisticTrain.main(MapReduceLogisticTrain.java:108)
>        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
>        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
>        at java.lang.reflect.Method.invoke(Method.java:597)
>        at org.apache.hadoop.util.ProgramDriver$ProgramDescription.invoke(ProgramDriver.java:68)
>        at org.apache.hadoop.util.ProgramDriver.driver(ProgramDriver.java:139)
>        at com.winvector.logistic.demo.DemoDriver.main(DemoDriver.java:21)
>        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
>        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
>        at java.lang.reflect.Method.invoke(Method.java:597)
>        at org.apache.hadoop.util.RunJar.main(RunJar.java:186)
> Exception in thread "main" java.lang.Exception: java.io.FileNotFoundException: File does not exist: /user/ameet/test.csv
>        at com.winvector.logistic.demo.DemoDriver.main(DemoDriver.java:25)
>        at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
>        at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:39)
>        at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:25)
>        at java.lang.reflect.Method.invoke(Method.java:597)
>        at org.apache.hadoop.util.RunJar.main(RunJar.java:186)
> 
> ---
> 
> Reply to this email directly or view it on GitHub:
> https://github.com/WinVector/SQL-Screwdriver/issues/1#issuecomment-4128327

---

John Mount
http://www.win-vector.com/
http://www.win-vector.com/blog/
jmount@win-vector.com

**Comment by WinVector** [comment]
achaubal, thanks for the feedback and I am sorry about the trouble you had.

**Comment by sunilaml** [comment]
Hi,
I am trying your tutorial provided at http://www.win-vector.com/blog/2010/12/large-data-logistic-regression-with-example-hadoop-code/.
After I run the following step....
(1) Downloaded and Extracted the file jar xvf WinVectorLogistic.Hadoop0.20.2.jar
(2) java -cp WinVectorLogistic.Hadoop0.20.2.jar:commons-logging-1.0.4.jar:commons-logging-api-1.0.4.jar \
com.winvector.logistic.demo.MapReduceLogisticTrain file:uciCarTrain.tsv "rating ~ buying + maintenance + doors + persons + lug_boot + safety" model.ser

I get following Error 

[root@localhost WinL]# java -cp WinVectorLogistic.Hadoop0.20.2.jar:commons-logging-1.0.4.jar:commons-logging-api-1.0.4.jar com.winvector.logistic.demo.MapReduceLogisticTrain file:uciCarTrain.tsv "rating ~ buying + maintenance + doors + persons + lug_boot + safety" model.ser
Exception in thread "main" java.lang.NoClassDefFoundError: org/apache/hadoop/util/Tool
        at java.lang.ClassLoader.defineClass1(Native Method)
        at java.lang.ClassLoader.defineClassCond(ClassLoader.java:631)
        at java.lang.ClassLoader.defineClass(ClassLoader.java:615)
        at java.security.SecureClassLoader.defineClass(SecureClassLoader.java:141)
        at java.net.URLClassLoader.defineClass(URLClassLoader.java:283)
        at java.net.URLClassLoader.access$000(URLClassLoader.java:58)
        at java.net.URLClassLoader$1.run(URLClassLoader.java:197)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
Caused by: java.lang.ClassNotFoundException: org.apache.hadoop.util.Tool
        at java.net.URLClassLoader$1.run(URLClassLoader.java:202)
        at java.security.AccessController.doPrivileged(Native Method)
        at java.net.URLClassLoader.findClass(URLClassLoader.java:190)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:306)
        at sun.misc.Launcher$AppClassLoader.loadClass(Launcher.java:301)
        at java.lang.ClassLoader.loadClass(ClassLoader.java:247)
        ... 12 more
Could not find the main class: com.winvector.logistic.demo.MapReduceLogisticTrain.  Program will exit.

Can you please help me in solving this issue. Thanks in advance.....

**Comment by WinVector** [comment]
sunilaml, to run the Hadoop based classes many of the Hadoop jars must already be in your classpath.  This is automatically true for some environments (like inside Amazon's Elastic Hadoop) and depends on your installation.  Sorry for the trouble.

**Comment by sunilaml** [comment]
Hello, Thanks for so quick reply.
Actually I am very new to Hadoop and Linux, and I am using Cloudera's demo VM (Centos 5.8 OS, with Hadoop-0.20.2 preinstalled) for learning Hadoop and packages related to it.
Can you please guide me on following doubts..... 
i) where I can find the classpath,
ii) how to load the Hadoop jars to the classpath,
iii)where to get them, and
iv) which are these jar.
Will be very thankful to you. Sorry for troubling you.

Regards,
Sunilaml

**Comment by sunilaml** [comment]
Hello,
Could someone help in resolving my problem stated above. Pl help.............

Regards,
Sunilaml
